// manifest.js — generated by gen/make-manifest.js. Key list + frame counts for integrity tests.
const SPRITE_LIST = [
  { key:'hale', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'hale_awakened', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'cinnia', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'tobin', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'marlowe', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'brant', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'nix', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'brigga', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'hearthgar', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'milla', w:48, h:48, frames:{idle:2,attack:3,hit:1,cast:2} },
  { key:'construct', w:40, h:48, frames:{idle:2,attack:2,hit:1} },
  { key:'hound', w:56, h:40, frames:{idle:2,attack:2,hit:1} },
  { key:'ox', w:72, h:56, frames:{idle:2,attack:2,hit:1} },
  { key:'calf', w:40, h:32, frames:{idle:2,attack:2,hit:1} },
  { key:'lowingman_beast', w:96, h:72, frames:{idle:2,attack:2,hit:1} },
  { key:'lowingman_man', w:96, h:72, frames:{idle:2,attack:2} },
  { key:'glasswright', w:48, h:56, frames:{idle:2,attack:2,hit:1} }
];
if (typeof module !== 'undefined' && module.exports) { module.exports = SPRITE_LIST; }
